// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: get_percentage_request.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct GetPercentageRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var flow: Float = 0

  var volumeStep: Int32 = 0

  var isFirstPackage: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension GetPercentageRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "GetPercentageRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "flow"),
    2: .same(proto: "volumeStep"),
    3: .same(proto: "isFirstPackage"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFloatField(value: &self.flow) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.volumeStep) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.isFirstPackage) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.flow != 0 {
      try visitor.visitSingularFloatField(value: self.flow, fieldNumber: 1)
    }
    if self.volumeStep != 0 {
      try visitor.visitSingularInt32Field(value: self.volumeStep, fieldNumber: 2)
    }
    if self.isFirstPackage != false {
      try visitor.visitSingularBoolField(value: self.isFirstPackage, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: GetPercentageRequest, rhs: GetPercentageRequest) -> Bool {
    if lhs.flow != rhs.flow {return false}
    if lhs.volumeStep != rhs.volumeStep {return false}
    if lhs.isFirstPackage != rhs.isFirstPackage {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
